version: "3.9"

services:
  web:
    container_name: web
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html

  php:
    container_name: php
    build: ./php
    environment:
      - APP_NAME=${APP_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./php/src:/var/www/html

  db:
    container_name: db
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql

  terraform:
    container_name: terraform
    build: ./terraform
    environment:
      - TF_VAR_app_name=${APP_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./terraform/src:/terraform
    profiles:
      - terraform

volumes:
  mysql-volume:
